### ISSUE TITLE
Adding a device into resources

### ISSUE THREAD

**Issue by marcelldls** [epics-containers/ec-helm-charts#34]
Allow device to be added into resources in the values.yaml without having to redefine the memory and cpu
```

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
      diamond.ac.uk/thorlabs-mff101: 1
    requests:
      cpu: 100m
      memory: 64Mi
      diamond.ac.uk/thorlabs-mff101: 1
  ```
