### ISSUE TITLE
Discoverability

### ISSUE THREAD

**Issue by gilesknap** [epics-containers/ec-helm-charts#35]
In the epics-containers workshops I said that from argocd downwards, all of the source code that makes up a beamline is discoverable.

However that is not true because the helm charts in this repo break the chain. e.g. by knowing that an IOC uses the ioc-template helm chart and what that charts oci: registry address is you do NOT get an indication of where the source for that helm chart came from.

I believe there are standards for labelling OCI assets that declare their origins. I think it would be nice for us to honour those standards. Furthermore our container images should also do so. Container images and source project name are very closely related and could most likely be inferred but again the is no real direct connection.

Marcell, would you like to take a look at this at some point? Clearly not an urgent issue but I like the argocd story and it would be better if it were actually true :-)

**Comment by marcelldls** [comment]
Good point @gilesknap . From https://helm.sh/docs/topics/charts/ 

# The Chart.yaml File

The Chart.yaml file is required for a chart. It contains the following fields:
```
apiVersion: The chart API version (required)
name: The name of the chart (required)
version: A SemVer 2 version (required)
kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
description: A single-sentence description of this project (optional)
type: The type of the chart (optional)
keywords:
  - A list of keywords about this project (optional)
home: The URL of this projects home page (optional)
sources:
  - A list of URLs to source code for this project (optional)
dependencies: # A list of the chart requirements (optional)
  - name: The name of the chart (nginx)
    version: The version of the chart ("1.2.3")
    repository: (optional) The repository URL ("https://example.com/charts") or alias ("@repo-name")
    condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
    tags: # (optional)
      - Tags can be used to group charts for enabling/disabling together
    import-values: # (optional)
      - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
    alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times
maintainers: # (optional)
  - name: The maintainers name (required for each maintainer)
    email: The maintainers email (optional for each maintainer)
    url: A URL for the maintainer (optional for each maintainer)
icon: A URL to an SVG or PNG image to be used as an icon (optional).
appVersion: The version of the app that this contains (optional). Needn't be SemVer. Quotes recommended.
deprecated: Whether this chart is deprecated (optional, boolean)
annotations:
  example: A list of annotations keyed by name (optional).
```
Looks like we can add `sources`,and possibly `maintainers` too. I think sources is enough
```
[esq51579@pc0146 b01-1-services]$ helm show chart oci://ghcr.io/epics-containers/ioc-instance --version 4.1.1+b1
Pulled: ghcr.io/epics-containers/ioc-instance:4.1.1_b1
Digest: sha256:08abbf16244ffc61f8d90e081fcdf6ac778bdbdf9e36f3fb4146c549b1566ab9
ghcr.io/epics-containers/ioc-instance:4.1.1_b1 contains an underscore.

OCI artifact references (e.g. tags) do not support the plus sign (+). To support
storing semantic versions, Helm adopts the convention of changing plus (+) to
an underscore (_) in chart version tags when pushing to a registry and back to
a plus (+) when pulling from a registry.
apiVersion: v2
appVersion: 4.1.1+b1
name: ioc-instance
sources:
- https://github.com/epics-containers/ec-helm-charts
type: application
version: 4.1.1+b1
```
Thoughts?
