### ISSUE TITLE
Consider "Kustomizing" ioc-instance

### ISSUE THREAD

**Issue by marcelldls** [epics-containers/ec-helm-charts#48]
Im partly making this as a record of my findings

Kustomize gives an ability to have a `configMapGenerator ` which adds a hash to the name of the config map across the Helm generated manifest. This can solve the problem of Pods not being restarted when the config map changes (Currently addressed with the `RollMe` random generation.

An example kustomization.yaml:
```
helmCharts:
  - name: ioc-instance
    repo: oci://ghcr.io/epics-containers
    version: 4.1.2
    additionalValuesFiles:
      - values.yaml
    releaseName: foo  # Need to repeat name in config - Not DRY
configMapGenerator:
  - name: foo-config  # Replaces mentions of foo-config with foo-config-<hash> in generated manifest
    files:
      - config/ioc.yaml  # Note: Globbing not permitted
```

We get the configmap we expect:
```
apiVersion: v1
data:
  ioc.yaml: |-
    # yaml-language-server: $schema=https://github.com/epics-containers/ioc-template-example/releases/download/4.0.0/ibek.ioc.schema.json

    ioc_name: "{{ _global.get_env('IOC_NAME') }}"

    description: Generic instance for testing generic IOCs

    entities:
      - type: epics.EpicsEnvSet
        name: EPICS_TZ
        value: "GMT0BST"

      - type: devIocStats.iocAdminSoft
        IOC: "{{ ioc_name | upper }}"

      - type: epics.StartupCommand
        command: dbLoadRecords("/epics/ioc/config/ioc.db")

      - type: epics.PostStartupCommand
        command: |
          dbpf P47:IBEK:A "2.54"
          dbpf P47:IBEK:B "2.61"
          dbgf P47:IBEK:SUM
kind: ConfigMap
metadata:
  name: foo-config-96h8t6tcdg
```
This supports the validity of our current practice of mounting our config in epics containers

There are some issues:
- The generated Configmaps are not garbage collected and must be manually pruned `https://github.com/kubernetes-sigs/kustomize/issues/1806`
- It is deployed using `kubectl apply -k <kustomization_directory>` therefore you dont get the Helm version control
- In kubectl (Client Version: v1.29.4 which ships with Kustomize Version: v5.0.4-) OCI registry not supported (Need to update)
- To support this in argocd we need to do `https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/#kustomizing-helm-charts`

Overall, it solves one problem but two more show up. I think its not the way forward. Thoughts @gilesknap?

**Comment by gilesknap** [comment]
hmmm.

- We are not getting helm version control with ArgoCD anyway - as far as I understand it so I don't see that as an issue if Argo CD is doing version tracking
- I assume we could make a job that prunes unused configMaps but that is a bit sad
- I bet we can get the ArgoCD plugin
- these I'm not keen on but I don't consider showstoppers
  - I don't mind the non-globbing too much - when you add files you can also add them to the manifest
  - I don't like repeating the IOC name and but we have gone to lots of trouble to avoid this in the past

I'm confused about the config map name though is it not always the same? if not why do we need cleaning up. - if so how do we mount it in the helm chart. 

Does this actually solve the hashing problem?

**Comment by gilesknap** [comment]
So does Kustomize also fix up references to the configMap - i.e. the volume definition?

**Comment by marcelldls** [comment]
> So does Kustomize also fix up references to the configMap - i.e. the volume definition?

Example manifest generated: (Short is yes)
```
 ./kustomize build --enable-helm services/example/
apiVersion: v1
data:
  ioc.yaml: |-
    # yaml-language-server: $schema=https://github.com/epics-containers/ioc-template-example/releases/download/4.0.0/ibek.ioc.schema.json

    ioc_name: "{{ _global.get_env('IOC_NAME') }}"

    description: Generic instance for testing generic IOCs

    entities:
      - type: epics.EpicsEnvSet
        name: EPICS_TZ
        value: "GMT0BST"

      - type: devIocStats.iocAdminSoft
        IOC: "{{ ioc_name | upper }}"

      - type: epics.StartupCommand
        command: dbLoadRecords("/epics/ioc/config/ioc.db")

      - type: epics.PostStartupCommand
        command: |
          dbpf P47:IBEK:A "2.54"
          dbpf P47:IBEK:B "2.61"
          dbgf P47:IBEK:SUM
kind: ConfigMap
metadata:
  name: foo-config-96h8t6tcdg
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: foo
    ioc_group: us
    is_ioc: "true"
    location: here
  name: foo-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: foo
    enabled: "true"
    ioc_group: us
    is_ioc: "true"
    location: here
  name: foo
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
        ioc_group: us
        is_ioc: "true"
        location: here
        rollme: ut68f
    spec:
      containers:
      - args:
        - /epics/ioc/start.sh
        command:
        - bash
        env:
        - name: IOCSH_PS1
          value: 'foo > '
        - name: IOC_NAME
          value: foo
        - name: IOC_PREFIX
          value: foo
        - name: IOC_LOCATION
          value: here
        - name: IOC_GROUP
          value: us
        image: ghcr.io/epics-containers/ioc-template-example-runtime:4.0.0
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - bash
              - -c
              - /epics/ioc/stop.sh
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /epics/ioc/liveness.sh
          initialDelaySeconds: 120
          periodSeconds: 10
        name: foo
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /epics/ioc/config
          name: config-volume
        - mountPath: /data
          mountPropagation: HostToContainer
          name: foo-data
        - mountPath: /epics/runtime
          name: runtime-volume
          subPath: foo
        - mountPath: /epics/opi
          name: opis-volume
          subPath: foo
        - mountPath: /autosave
          name: autosave-volume
          subPath: foo
      hostNetwork: true
      terminationGracePeriodSeconds: 3
      volumes:
      - name: runtime-volume
        persistentVolumeClaim:
          claimName: us-runtime-claim
      - name: opis-volume
        persistentVolumeClaim:
          claimName: us-opi-claim
      - name: autosave-volume
        persistentVolumeClaim:
          claimName: us-autosave-claim
      - name: foo-data
        persistentVolumeClaim:
          claimName: foo-data
      - configMap:
          name: foo-config-96h8t6tcdg
        name: config-volume
```
